# Generated by Django 2.2 on 2019-12-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserprofileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.AddField(
            model_name='diarymodel',
            name='polarity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diarymodel',
            name='subjectivity',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
