# Generated by Django 2.2 on 2019-12-29 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0002_auto_20191229_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarymodel',
            name='subjectivity',
        ),
    ]
