# Generated by Django 2.2 on 2019-12-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0003_remove_diarymodel_subjectivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarymodel',
            name='polarity',
            field=models.IntegerField(),
        ),
    ]
