# Generated by Django 2.2 on 2020-01-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0004_auto_20191229_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarymodel',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
