# Generated by Django 2.2 on 2020-01-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0005_diarymodel_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diarymodel',
            name='datetime',
        ),
    ]
